### PR TITLE
Sensor domain for energy sell/buy price

### PR DESCRIPTION
**Pull request by shiner66**
Permits the selection of sensors to indicate energy buy and sell prices to use directly prices coming from energy integrations, which are exposed as sensors

### CODE REVIEW

**Comment by jmcollin78** [comment]
Thank you @shiner66 !

**Comment by jmcollin78** [comment]
Unfortunately CI failed. Can you please have a look ?

**Comment by shiner66** [comment]
Hello, it seems to be an issue independent from my PR

`ERROR: Could not open requirements file: [Errno 2] No such file or directory: 'requirements_test.txt' `

**Comment by jmcollin78** [comment]
Maybe something have change on the HA CI steps. Are you able to have a look on what happens ?

**Comment by shiner66** [comment]
> Maybe something have change on the HA CI steps. Are you able to have a look on what happens ?

Again, I have no clue, I believe the error is caused by the CI itself, you should investigate your actions code.
I don't know how my commit could in any way cause the following command to fail(?), I'm very confused haha

`▶ Run python3 -m pip install -r requirements_test.txt`

**Comment by jmcollin78** [comment]
Will see that later. For now I merge.

**Pull request merged**
